name: Push the daily docker image

on:
    schedule:
        # https://crontab.guru/daily
        - cron: '0 0 * * *'
jobs:
    push_to_registry:
        name: Push the daily docker image to Docker Hub
        runs-on: ubuntu-latest
        steps:
            - name: Check out the repo
              uses: actions/checkout@v2
            - name: Log in to Docker Hub
              uses: docker/login-action@v1
              with:
                  username: ${{ secrets.DOCKER_USERNAME }}
                  password: ${{ secrets.DOCKER_PASSWORD }}

            - name: Push to Docker Hub
              uses: docker/build-push-action@v2
              with:
                  push: true
                  tags: hemmeligapp/hemmelig:daily
